// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:key_value_storage/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserCacheModelAdapter());
    registerAdapter(AuthorCacheModelAdapter());
    registerAdapter(CommentCacheModelAdapter());
    registerAdapter(CommentDataCacheModelAdapter());
    registerAdapter(CommentDestinationCacheModelAdapter());
    registerAdapter(CommentOriginCacheModelAdapter());
    registerAdapter(CommentPageCacheModelAdapter());
    registerAdapter(CommentStatisticsCacheModelAdapter());
    registerAdapter(MainTrunkPostOriginCacheModelAdapter());
    registerAdapter(PostCacheModelAdapter());
    registerAdapter(PostDataCacheModelAdapter());
    registerAdapter(PostPageCacheModelAdapter());
    registerAdapter(PostStatisticsCacheModelAdapter());
    registerAdapter(ReactionsCacheModelAdapter());
    registerAdapter(SpiderFetchDataCacheModelAdapter());
    registerAdapter(SpiderOembedDataCacheModelAdapter());
    registerAdapter(SpiderUrlDataCacheModelAdapter());
    registerAdapter(SubwikiCacheModelAdapter());
    registerAdapter(SubwikiListCacheModelAdapter());
    registerAdapter(SubwikiPostOriginCacheModelAdapter());
    registerAdapter(SubwikiStatisticsCacheModelAdapter());
    registerAdapter(TranslationCacheModelAdapter());
    registerAdapter(TrustObjectCacheModelAdapter());
    registerAdapter(UserProfilePostOriginCacheModelAdapter());
    registerAdapter(UserVoteCacheModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserCacheModelAdapter());
    registerAdapter(AuthorCacheModelAdapter());
    registerAdapter(CommentCacheModelAdapter());
    registerAdapter(CommentDataCacheModelAdapter());
    registerAdapter(CommentDestinationCacheModelAdapter());
    registerAdapter(CommentOriginCacheModelAdapter());
    registerAdapter(CommentPageCacheModelAdapter());
    registerAdapter(CommentStatisticsCacheModelAdapter());
    registerAdapter(MainTrunkPostOriginCacheModelAdapter());
    registerAdapter(PostCacheModelAdapter());
    registerAdapter(PostDataCacheModelAdapter());
    registerAdapter(PostPageCacheModelAdapter());
    registerAdapter(PostStatisticsCacheModelAdapter());
    registerAdapter(ReactionsCacheModelAdapter());
    registerAdapter(SpiderFetchDataCacheModelAdapter());
    registerAdapter(SpiderOembedDataCacheModelAdapter());
    registerAdapter(SpiderUrlDataCacheModelAdapter());
    registerAdapter(SubwikiCacheModelAdapter());
    registerAdapter(SubwikiListCacheModelAdapter());
    registerAdapter(SubwikiPostOriginCacheModelAdapter());
    registerAdapter(SubwikiStatisticsCacheModelAdapter());
    registerAdapter(TranslationCacheModelAdapter());
    registerAdapter(TrustObjectCacheModelAdapter());
    registerAdapter(UserProfilePostOriginCacheModelAdapter());
    registerAdapter(UserVoteCacheModelAdapter());
  }
}
